export interface ElementData {
  number: number;
  symbol: string;
  name: string;
  category: string;
  electronConfig: string;
  electronegativity?: number;
  atomicRadius?: number;
  group: number;
  period: number;
}

export const ELEMENTS: ElementData[] = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    category: "nonmetal",
    electronConfig: "1s¹",
    electronegativity: 2.2,
    atomicRadius: 53,
    group: 1,
    period: 1,
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    category: "noble-gas",
    electronConfig: "1s²",
    electronegativity: undefined,
    atomicRadius: 31,
    group: 18,
    period: 1,
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    category: "alkali-metal",
    electronConfig: "[He] 2s¹",
    electronegativity: 0.98,
    atomicRadius: 167,
    group: 1,
    period: 2,
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    category: "alkaline-earth",
    electronConfig: "[He] 2s²",
    electronegativity: 1.57,
    atomicRadius: 112,
    group: 2,
    period: 2,
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    category: "metalloid",
    electronConfig: "[He] 2s² 2p¹",
    electronegativity: 2.04,
    atomicRadius: 87,
    group: 13,
    period: 2,
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p²",
    electronegativity: 2.55,
    atomicRadius: 67,
    group: 14,
    period: 2,
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p³",
    electronegativity: 3.04,
    atomicRadius: 56,
    group: 15,
    period: 2,
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p⁴",
    electronegativity: 3.44,
    atomicRadius: 48,
    group: 16,
    period: 2,
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    category: "halogen",
    electronConfig: "[He] 2s² 2p⁵",
    electronegativity: 3.98,
    atomicRadius: 42,
    group: 17,
    period: 2,
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    category: "noble-gas",
    electronConfig: "[He] 2s² 2p⁶",
    electronegativity: undefined,
    atomicRadius: 38,
    group: 18,
    period: 2,
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    category: "alkali-metal",
    electronConfig: "[Ne] 3s¹",
    electronegativity: 0.93,
    atomicRadius: 190,
    group: 1,
    period: 3,
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    category: "alkaline-earth",
    electronConfig: "[Ne] 3s²",
    electronegativity: 1.31,
    atomicRadius: 145,
    group: 2,
    period: 3,
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    category: "post-transition",
    electronConfig: "[Ne] 3s² 3p¹",
    electronegativity: 1.61,
    atomicRadius: 118,
    group: 13,
    period: 3,
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    category: "metalloid",
    electronConfig: "[Ne] 3s² 3p²",
    electronegativity: 1.9,
    atomicRadius: 111,
    group: 14,
    period: 3,
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    category: "nonmetal",
    electronConfig: "[Ne] 3s² 3p³",
    electronegativity: 2.19,
    atomicRadius: 98,
    group: 15,
    period: 3,
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    category: "nonmetal",
    electronConfig: "[Ne] 3s² 3p⁴",
    electronegativity: 2.58,
    atomicRadius: 88,
    group: 16,
    period: 3,
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    category: "halogen",
    electronConfig: "[Ne] 3s² 3p⁵",
    electronegativity: 3.16,
    atomicRadius: 79,
    group: 17,
    period: 3,
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    category: "noble-gas",
    electronConfig: "[Ne] 3s² 3p⁶",
    electronegativity: undefined,
    atomicRadius: 71,
    group: 18,
    period: 3,
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    category: "alkali-metal",
    electronConfig: "[Ar] 4s¹",
    electronegativity: 0.82,
    atomicRadius: 243,
    group: 1,
    period: 4,
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    category: "alkaline-earth",
    electronConfig: "[Ar] 4s²",
    electronegativity: 1.0,
    atomicRadius: 194,
    group: 2,
    period: 4,
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    category: "transition-metal",
    electronConfig: "[Ar] 3d¹ 4s²",
    electronegativity: 1.36,
    atomicRadius: 184,
    group: 3,
    period: 4,
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    category: "transition-metal",
    electronConfig: "[Ar] 3d² 4s²",
    electronegativity: 1.54,
    atomicRadius: 176,
    group: 4,
    period: 4,
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    category: "transition-metal",
    electronConfig: "[Ar] 3d³ 4s²",
    electronegativity: 1.63,
    atomicRadius: 171,
    group: 5,
    period: 4,
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁵ 4s¹",
    electronegativity: 1.66,
    atomicRadius: 166,
    group: 6,
    period: 4,
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁵ 4s²",
    electronegativity: 1.55,
    atomicRadius: 161,
    group: 7,
    period: 4,
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁶ 4s²",
    electronegativity: 1.83,
    atomicRadius: 156,
    group: 8,
    period: 4,
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁷ 4s²",
    electronegativity: 1.88,
    atomicRadius: 152,
    group: 9,
    period: 4,
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    category: "transition-metal",
    electronConfig: "[Ar] 3d⁸ 4s²",
    electronegativity: 1.91,
    atomicRadius: 149,
    group: 10,
    period: 4,
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    category: "transition-metal",
    electronConfig: "[Ar] 3d¹⁰ 4s¹",
    electronegativity: 1.9,
    atomicRadius: 145,
    group: 11,
    period: 4,
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    category: "transition-metal",
    electronConfig: "[Ar] 3d¹⁰ 4s²",
    electronegativity: 1.65,
    atomicRadius: 142,
    group: 12,
    period: 4,
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    category: "post-transition",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronegativity: 1.81,
    atomicRadius: 136,
    group: 13,
    period: 4,
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    category: "metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p²",
    electronegativity: 2.01,
    atomicRadius: 125,
    group: 14,
    period: 4,
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    category: "metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p³",
    electronegativity: 2.18,
    atomicRadius: 114,
    group: 15,
    period: 4,
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    category: "nonmetal",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronegativity: 2.55,
    atomicRadius: 103,
    group: 16,
    period: 4,
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    category: "halogen",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronegativity: 2.96,
    atomicRadius: 94,
    group: 17,
    period: 4,
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    category: "noble-gas",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁶",
    electronegativity: 3.0,
    atomicRadius: 88,
    group: 18,
    period: 4,
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    category: "alkali-metal",
    electronConfig: "[Kr] 5s¹",
    electronegativity: 0.82,
    atomicRadius: 265,
    group: 1,
    period: 5,
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    category: "alkaline-earth",
    electronConfig: "[Kr] 5s²",
    electronegativity: 0.95,
    atomicRadius: 219,
    group: 2,
    period: 5,
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    category: "transition-metal",
    electronConfig: "[Kr] 4d¹ 5s²",
    electronegativity: 1.22,
    atomicRadius: 212,
    group: 3,
    period: 5,
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    category: "transition-metal",
    electronConfig: "[Kr] 4d² 5s²",
    electronegativity: 1.33,
    atomicRadius: 206,
    group: 4,
    period: 5,
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁴ 5s¹",
    electronegativity: 1.6,
    atomicRadius: 198,
    group: 5,
    period: 5,
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁵ 5s¹",
    electronegativity: 2.16,
    atomicRadius: 190,
    group: 6,
    period: 5,
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁵ 5s²",
    electronegativity: 1.9,
    atomicRadius: 183,
    group: 7,
    period: 5,
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁷ 5s¹",
    electronegativity: 2.2,
    atomicRadius: 178,
    group: 8,
    period: 5,
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    category: "transition-metal",
    electronConfig: "[Kr] 4d⁸ 5s¹",
    electronegativity: 2.28,
    atomicRadius: 173,
    group: 9,
    period: 5,
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    category: "transition-metal",
    electronConfig: "[Kr] 4d¹⁰",
    electronegativity: 2.2,
    atomicRadius: 169,
    group: 10,
    period: 5,
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    category: "transition-metal",
    electronConfig: "[Kr] 4d¹⁰ 5s¹",
    electronegativity: 1.93,
    atomicRadius: 165,
    group: 11,
    period: 5,
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    category: "transition-metal",
    electronConfig: "[Kr] 4d¹⁰ 5s²",
    electronegativity: 1.69,
    atomicRadius: 161,
    group: 12,
    period: 5,
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    category: "post-transition",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p¹",
    electronegativity: 1.78,
    atomicRadius: 156,
    group: 13,
    period: 5,
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    category: "post-transition",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p²",
    electronegativity: 1.96,
    atomicRadius: 145,
    group: 14,
    period: 5,
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    category: "metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p³",
    electronegativity: 2.05,
    atomicRadius: 133,
    group: 15,
    period: 5,
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    category: "metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁴",
    electronegativity: 2.1,
    atomicRadius: 123,
    group: 16,
    period: 5,
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    category: "halogen",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁵",
    electronegativity: 2.66,
    atomicRadius: 115,
    group: 17,
    period: 5,
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    category: "noble-gas",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁶",
    electronegativity: 2.6,
    atomicRadius: 108,
    group: 18,
    period: 5,
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Caesium",
    category: "alkali-metal",
    electronConfig: "[Xe] 6s¹",
    electronegativity: 0.79,
    atomicRadius: 298,
    group: 1,
    period: 6,
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    category: "alkaline-earth",
    electronConfig: "[Xe] 6s²",
    electronegativity: 0.89,
    atomicRadius: 253,
    group: 2,
    period: 6,
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    category: "lanthanide",
    electronConfig: "[Xe] 5d¹ 6s²",
    electronegativity: 1.1,
    atomicRadius: 195,
    group: 3,
    period: 6,
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹ 5d¹ 6s²",
    electronegativity: 1.12,
    atomicRadius: 185,
    group: 4,
    period: 6,
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    category: "lanthanide",
    electronConfig: "[Xe] 4f³ 6s²",
    electronegativity: 1.13,
    atomicRadius: 247,
    group: 5,
    period: 6,
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁴ 6s²",
    electronegativity: 1.14,
    atomicRadius: 206,
    group: 6,
    period: 6,
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    electronegativity: 2.54,
    atomicRadius: 174,
    group: 11,
    period: 6,
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    category: "transition-metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    electronegativity: 2.0,
    atomicRadius: 171,
    group: 12,
    period: 6,
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    electronegativity: 1.62,
    atomicRadius: 156,
    group: 13,
    period: 6,
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    electronegativity: 2.33,
    atomicRadius: 154,
    group: 14,
    period: 6,
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    electronegativity: 2.02,
    atomicRadius: 143,
    group: 15,
    period: 6,
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    category: "metalloid",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    electronegativity: 2.0,
    atomicRadius: 135,
    group: 16,
    period: 6,
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    category: "halogen",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    electronegativity: 2.2,
    atomicRadius: 127,
    group: 17,
    period: 6,
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    category: "noble-gas",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    electronegativity: 2.2,
    atomicRadius: 120,
    group: 18,
    period: 6,
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    category: "alkali-metal",
    electronConfig: "[Rn] 7s¹",
    electronegativity: 0.7,
    atomicRadius: 348,
    group: 1,
    period: 7,
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    category: "alkaline-earth",
    electronConfig: "[Rn] 7s²",
    electronegativity: 0.9,
    atomicRadius: 283,
    group: 2,
    period: 7,
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    category: "actinide",
    electronConfig: "[Rn] 6d¹ 7s²",
    electronegativity: 1.1,
    atomicRadius: 195,
    group: 3,
    period: 7,
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    category: "actinide",
    electronConfig: "[Rn] 6d² 7s²",
    electronegativity: 1.3,
    atomicRadius: 180,
    group: 4,
    period: 7,
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    category: "actinide",
    electronConfig: "[Rn] 5f³ 6d¹ 7s²",
    electronegativity: 1.38,
    atomicRadius: 196,
    group: 6,
    period: 7,
  },
];

export const CATEGORY_COLORS: Record<
  string,
  { bg: string; text: string; label: string }
> = {
  "alkali-metal": { bg: "#fee2e2", text: "#991b1b", label: "Alkali Metal" },
  "alkaline-earth": { bg: "#fef3c7", text: "#92400e", label: "Alkaline Earth" },
  "transition-metal": {
    bg: "#dbeafe",
    text: "#1e40af",
    label: "Transition Metal",
  },
  "post-transition": {
    bg: "#d1fae5",
    text: "#065f46",
    label: "Post-transition",
  },
  metalloid: { bg: "#e0e7ff", text: "#3730a3", label: "Metalloid" },
  nonmetal: { bg: "#fce7f3", text: "#9d174d", label: "Nonmetal" },
  halogen: { bg: "#f3e8ff", text: "#6b21a8", label: "Halogen" },
  "noble-gas": { bg: "#ccfbf1", text: "#115e59", label: "Noble Gas" },
  lanthanide: { bg: "#fef9c3", text: "#854d0e", label: "Lanthanide" },
  actinide: { bg: "#ffe4e6", text: "#9f1239", label: "Actinide" },
};
