/**
 * Cloudflare env/binding type augmentation (Wave E.1 "Ask Kanit").
 *
 * `env.d.ts` is gitignored in this repo (generated by `wrangler types`), so
 * the bindings this feature consumes are declared here in a committed file.
 * The augmentation merges into the global `CloudflareEnv` interface that
 * opennextjs-cloudflare exposes via `getCloudflareContext().env`.
 *
 * `AI` — the Workers AI binding (see docs/agent-setup.md for wiring it in
 * wrangler.jsonc). Optional so the app still boots when bindings are absent
 * (local dev / tests degrade to a "coming soon" stub instead of crashing).
 */

declare global {
  interface AiEmbeddingInput {
    text: string | string[];
  }
  interface AiEmbeddingResult {
    data: { embedding: number[] }[];
  }
  interface AiTextGenerationInput {
    messages?: { role: string; content: string }[];
    prompt?: string;
    stream?: boolean;
    [key: string]: unknown;
  }
  interface AiTextGenerationResult {
    response?: string;
    [key: string]: unknown;
  }
  /** Streaming generation returns a ReadableStream of JSON `{"response":"…"}` chunks. */
  interface AiTextGenerationStreamResult {
    getReader(): {
      read(): Promise<{ done: boolean; value?: Uint8Array }>;
      cancel?(): Promise<void>;
    };
  }
  interface Ai {
    run(model: string, inputs: AiEmbeddingInput): Promise<AiEmbeddingResult>;
    run(
      model: string,
      inputs: AiTextGenerationInput & { stream: true }
    ): Promise<AiTextGenerationStreamResult>;
    run(
      model: string,
      inputs: AiTextGenerationInput
    ): Promise<AiTextGenerationResult>;
    run(model: string, inputs: unknown): Promise<unknown>;
  }

  interface CloudflareEnv {
    AI?: Ai;
    CF_TURNSTILE_SECRET?: string;
  }
}

export {};
