import { netstarDiagram } from "@/data/diagrams/netstar";
import { unified_bharatDiagram } from "@/data/diagrams/unified-bharat";
import { ericssonDiagram } from "@/data/diagrams/ericsson";

/**
 * Build-time-rendered Mermaid diagrams, keyed by project slug. Each value is
 * a static SVG string generated by `npm run render:diagrams` — no client JS
 * is shipped for diagrams.
 */
export const projectDiagrams: Record<string, string> = {
  netstar: netstarDiagram,
  "unified-bharat": unified_bharatDiagram,
  ericsson: ericssonDiagram,
};
